[package]
name = "tooka"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4", features = ["derive"] }
directories-next = "2.0.0"
kamadak-exif = "0.6.1"
log = "0.4.27"
mime_guess = "2.0.5"
regex = "1.11.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_yaml = "0.9.34"
simplelog = "0.12.2"
users = "0.11.0"
walkdir = "2.5.0"
