[package]
name = "tooka"
version = "0.1.2"
description = "A fast, rule-based CLI tool for organizing your files"
authors = ["Benjamin Demetz"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/Benji377/tooka"
homepage = "https://tooka.deno.dev"
keywords = ["tooka", "filesystem", "cli", "utility", "automation"]
categories = ["command-line-utilities", "filesystem", "utilities", "productivity"]
default-run = "tooka"
edition = "2024"
rust-version = "1.87"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4", features = ["derive"] }
clap_complete = "4.5.50"
csv = "1.3.1"
directories-next = "2.0.0"
flate2 = "1.1.1"
flexi_logger = "0.30.1"
genpdf = { version = "0.2.0", features = ["images"] }
glob = "0.3.2"
indicatif = "0.17.11"
kamadak-exif = "0.6.1"
lazy_static = "1.5.0"
log = "0.4.27"
mime_guess = "2.0.5"
rayon = "1.10.0"
regex = "1.11.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
serde_yaml = "0.9.34"
shellexpand = "3.1.1"
simplelog = "0.12.2"
thiserror = "2.0.12"
walkdir = "2.5.0"

[target.'cfg(unix)'.dependencies]
users = "0.11.0"


[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[package.metadata.packager]
product-name = "tooka"
identifier = "io.github.benji377.tooka"
category = "Utility"
homepage = "https://tooka.deno.dev"
icons = ["assets/logo.png"]
licenseFile = "LICENSE"
formats = ["all"]
before-packaging-command = "cargo build --release"
