name: tooka
base: core24
version: git
summary: A fast, rule-based CLI tool for organizing your files.
description: Tooka is a powerful file automation tool that helps you organize, rename, move, copy, compress, or delete files using rules written in simple YAML format.
icon: assets/logo.svg
grade: stable
confinement: strict
platforms:
  all:
    build-on: [amd64] 
    build-for: [all]

parts:
  tooka:
    plugin: rust
    source: .
    rust-channel: "stable"
    rust-cargo-parameters: ["-p tooka-cli"]

#  desktop-files:
#    plugin: dump
#    source: data
#    organize:
#      tooka.desktop: usr/share/applications/tooka.desktop
#      tooka.metainfo.xml: usr/share/metainfo/tooka.metainfo.xml
#      tooka.svg: usr/share/applications/tooka.svg

apps:
  tooka:
    command: usr/bin/tooka
    plugs:
      - home
      - removable-media
      - optical-drive
