name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTC_BOOTSTRAP: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable

    - name: Rust cache
      uses: swatinem/rust-cache@v2

    - name: Pre-Check the code
      run: cargo check --verbose

    - name: Install cargo2junit
      run: cargo install cargo2junit

    - name: Run tests and convert to JUnit
      run: cargo test -p tooka-core -- --format json --report-time | cargo2junit > test-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}   
      with:
        name: test-results
        path: test-results.xml

    - name: Publish test results to GitHub UI
      uses: dorny/test-reporter@v2
      if: always()
      with:
        artifact: test-results
        name: Rust Tests
        path: '*.xml'
        reporter: java-junit